### ISSUE TITLE
Enabling this conf?

### ISSUE THREAD

**Issue by guerillaengineer** [seedboxer/itconfigPI#1]
Hello precious pimp, I was wondering if there was another way to enable this other than compiling the ltconfig.egg?

I'm most likely missing something obvious, so I thought I'd reach out to the person so knowledgeable they crafted their own config haha.

I will say that I went through core.conf and changed a few values to match, then went through the ltconfig plugin and edited a few things as well. Running this on an Orange pi 3b with nvme SSD so I can hopefully increase a few performance values!

Please be well, thank you for reading, and I hope to hear from you!

**Comment by seedboxer** [comment]
Hi

Sorry can no longer remember now using qBitTorrent.

Pretty sure you dont need to compile however just edit the config on the server id think.

The point of these settings was not to overload the device, rather than pure speed.

I.e You can get 30-40Mb/s with out crashing out the device.

I do not know about the Orange pi 3b, but the problem with the PI was always available speed via USB rather than the attached device, the issue was always keeping it alive so it could deliver other services whilst reaching the highest speeds possible rather than stalling.

thanks

**Comment by guerillaengineer** [comment]
Thanks a ton! I'm planning in getting this on an old rock64 as well so I appreciate your response. have a great one

**Comment by seedboxer** [comment]
I recommend Dietpi 

https://github.com/MichaIng/DietPi
